name: shop_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.2
  cupertino_icons: ^0.1.3
  material_design_icons_flutter: ^4.0.5345
  icons_helper: ^1.0.4
  flutter_svg: ^0.17.4
  dart_json_mapper: ^1.5.16
  dart_json_mapper_flutter: ^1.0.1 # complementary package; provides support for Flutter types
  intl: ^0.16.1 #dart_json_mapper needs this
  reflectable: ^2.2.5 #dart_json_mapper needs this

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  build_test: ^0.10.3
  json_serializable: ^3.2.5

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # assets/images/facilities: <a href="https://www.vecteezy.com/free-vector/factory">Factory Vectors by Vecteezy</a>
    - assets/images/facilities/
    - assets/images/rpg_image_pack/
    - assets/images/rpg_image_pack/addons/
    - assets/images/rpg_image_pack/cloth/
    - assets/images/rpg_image_pack/gems/
    - assets/images/rpg_image_pack/herbs/
    - assets/images/rpg_image_pack/ingots/
    - assets/images/rpg_image_pack/leather/
    - assets/images/rpg_image_pack/packs/
    - assets/images/rpg_image_pack/parts/
    - assets/images/rpg_image_pack/potion/
    - assets/images/rpg_image_pack/reagents/
    - assets/images/rpg_image_pack/stone/
    - assets/images/rpg_image_pack/wood/
    - assets/icons/
    - assets/json/facility-data.json
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: EmployeeIcons
      fonts:
        - asset: assets/fonts/EmployeeIcons.ttf
        # attribution can be found in lib/models/employee_icons.dart
    - family: FacilityIcons
      fonts:
        - asset: assets/fonts/FacilityIcons.ttf
        # attribution can be found in lib/models/facility_icons.dart
    - family: ProductIcons
      fonts:
        - asset: assets/fonts/ProductIcons.ttf
        # attribution can be found in lib/models/product_icons.dart
    - family: ResearchIcons
      fonts:
        - asset: assets/fonts/ProjectIcons.ttf
        # attribution can be found in lib/models/project_icons.dart