/// Flutter icons EmployeeIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EmployeeIcons
///      fonts:
///       - asset: fonts/EmployeeIcons.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class EmployeeIcons {
  EmployeeIcons._();

  static const _kFontFam = 'EmployeeIcons';
  static const _kFontPkg = null;

  static const IconData teammember = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg); // group
  static const IconData teamleader = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg); // person
  static const IconData director = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);   // crown
  static const IconData manager = IconData(0xf3c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);    // person_1
}
