/// Flutter icons ProductIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ProductIcons
///      fonts:
///       - asset: fonts/Product_Icons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class ProductIcons {
  ProductIcons._();

  static const _kFontFam = 'ProductIcons';
  static const _kFontPkg = null;

  static const IconData drone = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);          // android
  static const IconData utility = IconData(0xea85, fontFamily: _kFontFam, fontPackage: _kFontPkg);        // robot_arm
  static const IconData offense = IconData(0xf388, fontFamily: _kFontFam, fontPackage: _kFontPkg);        // rocket
  static const IconData defense = IconData(0xf3ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);        // shield_alt
  static const IconData transport = IconData(0xf4df, fontFamily: _kFontFam, fontPackage: _kFontPkg);      // truck_moving
  static const IconData gadget = IconData(0xf544, fontFamily: _kFontFam, fontPackage: _kFontPkg);         // robot
}
