/// Flutter icons ResearchIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ResearchIcons
///      fonts:
///       - asset: fonts/Project_Icons.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class ProjectIcons {
  ProjectIcons._();

  static const _kFontFam = 'ProjectIcons';
  static const _kFontPkg = null;

  static const IconData type_1 = IconData(0xf329, fontFamily: _kFontFam, fontPackage: _kFontPkg);               // beaker
  static const IconData type_2 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);             // beaker_1
  static const IconData type_3 = IconData(0xf0c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);             // beaker_2
  static const IconData level_1 = IconData(0xea28, fontFamily: _kFontFam, fontPackage: _kFontPkg);            // level_two
  static const IconData level_2 = IconData(0xea27, fontFamily: _kFontFam, fontPackage: _kFontPkg);   // level_two_advanced
  static const IconData level_3 = IconData(0xea26, fontFamily: _kFontFam, fontPackage: _kFontPkg);          // level_three
  static const IconData level_4 = IconData(0xea25, fontFamily: _kFontFam, fontPackage: _kFontPkg); // level_three_advanced
  static const IconData level_5 = IconData(0xea24, fontFamily: _kFontFam, fontPackage: _kFontPkg);           // level_four
  static const IconData level_6 = IconData(0xea23, fontFamily: _kFontFam, fontPackage: _kFontPkg);  // level_four_advanced
}
