/// Flutter icons FacilityIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FacilityIcons
///      fonts:
///       - asset: fonts/FacilityIcons.ttf
///
/// 
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FacilityIcons {
  FacilityIcons._();

  static const _kFontFam = 'FacilityIcons';
  static const _kFontPkg = null;

  static const IconData tier_2 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);  // commercial_building
  static const IconData tier_1 = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);  // industrial_building
  static const IconData tier_4 = IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);  // building_filled
  static const IconData tier_3 = IconData(0xf0f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);  // building
  static const IconData tier_5 = IconData(0xf1ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);  // building_1
}
